### PR TITLE
Fix

### LINKED ISSUE #6: Login and Signin
I wanted to try "issues".

traitement.php has a problem. It always creates a new account when you login.
It looks like the select doesn't find that the user's email already exists.

Help me solve this issue please.
Thanks

### PR DESCRIPTION
**Pull request by LarochelleJ**
SQL file will need to be updated with a file that reflects the actual database structure

### CODE REVIEW

File: traitement-login.php [hunk 1]
```diff
@@ -40,9 +40,10 @@
     {
         $messageErreur .= 'Le mot de passe est requis.<br />';
     }
-    elseif (mb_strlen($password) > 100)//Si la variable est plus grande que 100 caracteres
+    elseif (strlen($password) > 72) //Si la variable est plus grande que 72 bytes
```
Comment (2143781-Ouellette-Antoine) [inline traitement-login.php:43]: Pourquoi 72?

File: traitement-login.php [hunk 2]
```diff
@@ -40,9 +40,10 @@
...
     {
-        $messageErreur .= 'Le mot de passe depasse 100 caracteres.<br />';
+        // BCRYPT est limité à 72 bytes
+        $messageErreur .= 'Le mot de passe est trop long<br />';
```
Comment (Antoine-Ouellette) [inline traitement-login.php:46]: Dire que c'est 72

**Review by Antoine-Ouellette — APPROVED** [review]
